### ISSUE TITLE
Error log when run nextcloud-file-sync.sh

### ISSUE THREAD

**Issue by liejuntao001** [GAS85/nextcloud_scripts#1]
Nextcloud 18.0.4

[PHP] Error: Undefined index: reqId at /var/www/html/apps/logreader/lib/Controller/LogController.php#115

Problem:
echo \{\"app\":\"$COMMAND $OPTIONS\",\"message\":\""+++ Starting Cron Filescan +++"\",\"level\":1,\"time\":\"`date "+%Y-%m-%dT%H:%M:%S%:z"`\"\} >> $LOGFILE

Fix:

echo \{\"reqId\":\"dummy\",\"app\":\"$COMMAND $OPTIONS\",\"message\":\""+++ Starting Cron Filescan +++"\",\"level\":1,\"time\":\"`date "+%Y-%m-%dT%H:%M:%S%:z"`\"\} >> $LOGFILE

**Comment by GAS85** [comment]
Thanks! I added even random reqid to the script to be align with guidelines.
