### ISSUE TITLE
wrong cron time format

### ISSUE THREAD

**Issue by liejuntao001** [GAS85/nextcloud_scripts#2]
* */1 * * * /usr/local/bin/nextcloud-file-sync.sh

This means to do the cronjob every minute in every hour

To do it every hour
5 */1 * * * /usr/local/bin/nextcloud-file-sync.sh
or 
5 * * * * /usr/local/bin/nextcloud-file-sync.sh

**Comment by GAS85** [comment]
Thanks for noticing it 👍
