### ISSUE TITLE
How do you install

### ISSUE THREAD

**Issue by ghost** [GAS85/nextcloud_scripts#5]
I am not the best with occ, can you help me install all of the scripts.

**Comment by GAS85** [comment]
Scripts should be simply saved in a some folder, e.g. `/usr/local/bin/`. Configuration `nextcloud-scripts-config.conf` file is usually expected under the same folder as script is located.

You have to set [755](https://chmodcommand.com/chmod-755/) or [555](https://chmodcommand.com/chmod-555/) permissions) to the scripts and e.g. [444](https://chmodcommand.com/chmod-444/) for a configuration file.

All scripts are to be executed separately via cron job, or command line.
