### ISSUE TITLE
ERROR - PHP not found, or not executable.

### ISSUE THREAD

**Issue by wwwwiii** [GAS85/nextcloud_scripts#7]
# Your PHP location
PHP=/etc/php/7.4/fpm/php.ini

when running as; sudo -u www-data ./nextcloud-file-sync.sh

what am i doing wrong? or is this a bug?

**Comment by wwwwiii** [comment]
also have this file set up: nextcloud-scripts-config.conf;

COMMAND=/usr/share/nginx/nextcloud/occ
LOGFILE=/usr/share/nginx/nextcloud/data/nextcloud.log
CRONLOGFILE=/var/log/next-cron.log
PHP=/etc/php/7.4/fpm/php

**Comment by wwwwiii** [comment]
nvm fixed it already :D

 PHP=/usr/bin/php7.4

**Comment by GAS85** [comment]
Glad for U!
